#!/bin/sh

no_prompt=`test $1 && test '--no-prompt' = $1 && echo true`

test $no_prompt && read -p "This will delete ~/.bash_profile, ~/.inputrc and ~/.ps1 press y to proceed: " confirm

dir=$(cd $(dirname $0); pwd)

(test $no_prompt || test $confirm = 'y' -o $confirm = 'Y') && {

  rm -rf $HOME/.ps1
  ln -s "$dir/ps1.sh" $HOME/.ps1

  rm -rf $HOME/.bash_profile
  ln -s "$dir/profile.sh" $HOME/.bash_profile

  rm -rf $HOME/.inputrc
  ln -s "$dir/inputrc" $HOME/.inputrc
}
